#!/bin/sh 

# pegasus/src/Pegasus/Common/TraceComponents.h contains the component list

# Channel, XmlParser, XmlWriter, XmlReader, XmlIO, Http, CimData, ProvManager, Repository, Dispatcher, OsAbstraction, Config, IndDelivery, IndHandler, Authentication, Authorization, UserManager, SubscriptionService, Registration, Shutdown, Server, IndicationService, IndicationServiceInternal, ConfigurationManager, MessageQueueService, ProviderManager, ObjectResolution, WQL, CQL, Thread, MetaDispatcher, IPC, IndicationHandlerService, CIMExportRequestDispatcher, Memory, SSL, ControlProvider, AsyncOpNode, CIMOMHandle, BinaryMessageHandler, L10N, ExportClient, Listener, DiscardedData, ProviderAgent, IndicationFormatter, StatisticalData


MY_TRACE=\
Channel,\
XmlParser,\
XmlWriter,\
XmlReader,\
XmlIO,\
Http,\
CimData,\
ProvManager,\
Repository,\
OsAbstraction,\
Config,\
IndDelivery,\
IndHandler,\
UserManager,\
SubscriptionService,\
Registration,\
Shutdown,\
Server,\
IndicationService,\
IndicationServiceInternal,\
ConfigurationManager,\
MessageQueueService,\
ProviderManager,\
ObjectResolution,\
WQL,\
CQL,\
MetaDispatcher,\
IPC,\
IndicationHandlerService,\
CIMExportRequestDispatcher,\
Memory,\
SSL,\
ControlProvider,\
AsyncOpNode,\
CIMOMHandle,\
BinaryMessageHandler,\
ExportClient,\
Listener,\
DiscardedData,\
ProviderAgent,\
IndicationFormatter,\
StatisticalData

# Currently diabled: 
#Thread,\
#L10N,\
#Authentication,\
#Authorization,\
#Dispatcher,\


cimconfig -s traceLevel=4
cimconfig -s traceLevel=4 -p
cimconfig -s traceComponents=${MY_TRACE}
cimconfig -s traceComponents=${MY_TRACE} -p
cimconfig -s logLevel=INFORMATION
cimconfig -s logLevel=INFORMATION -p
# Not supported for current session
cimconfig -s enableHttpConnection=true -p
