#!/bin/sh

# This script can be used to replace binaries of an installed tog-pegasus (RPM) with 
# home-compiled ones.

ROOT_DIR=~andreas/dev/tfs/scx_core
PLATFORM_STRING=Linux_SLES10_x86_32_Debug
#ROOT_DIR=~andreas/dev/sfcc_replacement/scx_core
TARGET_STAGING_ROOT_DIR=$ROOT_DIR/target/$PLATFORM_STRING
PEG_STAGING_ROOT_DIR=$ROOT_DIR/intermediate/$PLATFORM_STRING/pegasus
WSM_STAGING_ROOT_DIR=$ROOT_DIR/intermediate/$PLATFORM_STRING/openwsman


# bin dir

rm /opt/microsoft/scx/bin/tools/cimconfig; ln -s $PEG_STAGING_ROOT_DIR/bin/cimconfig /opt/microsoft/scx/bin/tools/cimconfig
rm /opt/microsoft/scx/bin/tools/cimmof; ln -s $PEG_STAGING_ROOT_DIR/bin/cimmof /opt/microsoft/scx/bin/tools/cimmof
rm /opt/microsoft/scx/bin/tools/cimmofl; ln -s $PEG_STAGING_ROOT_DIR/bin/cimmofl /opt/microsoft/scx/bin/tools/cimmofl
rm /opt/microsoft/scx/bin/tools/cimcli; ln -s $PEG_STAGING_ROOT_DIR/bin/cimcli /opt/microsoft/scx/bin/tools/cimcli
rm /opt/microsoft/scx/bin/cimprovagt; ln -s $PEG_STAGING_ROOT_DIR/bin/cimprovagt /opt/microsoft/scx/bin/cimprovagt
rm /opt/microsoft/scx/bin/cimprovider; ln -s $PEG_STAGING_ROOT_DIR/bin/cimprovider /opt/microsoft/scx/bin/cimprovider
rm /opt/microsoft/scx/bin/cimserver; ln -s $PEG_STAGING_ROOT_DIR/bin/cimserver /opt/microsoft/scx/bin/cimserver
rm /opt/microsoft/scx/bin/openwsmand; ln -s $WSM_STAGING_ROOT_DIR/sbin/openwsmand /opt/microsoft/scx/bin/openwsmand


# lib dir 
# rm /opt/microsoft/scx/lib/libcimcclient.so.0; ln -s $ROOT_DIR/source/ext/lib/linux/ia32/sblim-sfcc/libcimcclient.so.0 /opt/microsoft/scx/lib/libcimcclient.so.0
# rm /opt/microsoft/scx/lib/libcimcClientXML.so; ln -s $ROOT_DIR/source/ext/lib/linux/ia32/sblim-sfcc/libcimcClientXML.so /opt/microsoft/scx/lib/libcimcClientXML.so
rm /opt/microsoft/scx/lib/providers/libCIMOMStatDataProvider.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libCIMOMStatDataProvider.so /opt/microsoft/scx/lib/providers/libCIMOMStatDataProvider.so
rm /opt/microsoft/scx/lib/providers/libCIMOMStatDataProvider.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libCIMOMStatDataProvider.so /opt/microsoft/scx/lib/providers/libCIMOMStatDataProvider.so.1
rm /opt/microsoft/scx/lib/providers/libCIMQueryCapabilitiesProvider.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libCIMQueryCapabilitiesProvider.so /opt/microsoft/scx/lib/providers/libCIMQueryCapabilitiesProvider.so
rm /opt/microsoft/scx/lib/providers/libCIMQueryCapabilitiesProvider.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libCIMQueryCapabilitiesProvider.so /opt/microsoft/scx/lib/providers/libCIMQueryCapabilitiesProvider.so.1
rm /opt/microsoft/scx/lib/libCIMxmlIndicationHandler.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libCIMxmlIndicationHandler.so /opt/microsoft/scx/lib/libCIMxmlIndicationHandler.so
rm /opt/microsoft/scx/lib/libCIMxmlIndicationHandler.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libCIMxmlIndicationHandler.so /opt/microsoft/scx/lib/libCIMxmlIndicationHandler.so.1
rm /opt/microsoft/scx/lib/libcmpiCppImpl.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libcmpiCppImpl.so /opt/microsoft/scx/lib/libcmpiCppImpl.so
rm /opt/microsoft/scx/lib/libcmpiCppImpl.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libcmpiCppImpl.so /opt/microsoft/scx/lib/libcmpiCppImpl.so.1
rm /opt/microsoft/scx/lib/libcmpiCWS_Util.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libcmpiCWS_Util.so /opt/microsoft/scx/lib/libcmpiCWS_Util.so
rm /opt/microsoft/scx/lib/libcmpiCWS_Util.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libcmpiCWS_Util.so /opt/microsoft/scx/lib/libcmpiCWS_Util.so.1
rm /opt/microsoft/scx/lib/libCMPIProviderManager.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libCMPIProviderManager.so /opt/microsoft/scx/lib/libCMPIProviderManager.so
rm /opt/microsoft/scx/lib/libCMPIProviderManager.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libCMPIProviderManager.so /opt/microsoft/scx/lib/libCMPIProviderManager.so.1
# rm /opt/microsoft/scx/lib/libcmpisfcc.so.1; ln -s $ROOT_DIR/source/ext/lib/linux/ia32/sblim-sfcc/libcmpisfcc.so.1 /opt/microsoft/scx/lib/libcmpisfcc.so.1
rm /opt/microsoft/scx/lib/libcmpiUtilLib.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libcmpiUtilLib.so /opt/microsoft/scx/lib/libcmpiUtilLib.so
rm /opt/microsoft/scx/lib/libcmpiUtilLib.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libcmpiUtilLib.so /opt/microsoft/scx/lib/libcmpiUtilLib.so.1
rm /opt/microsoft/scx/lib/providers/libConfigSettingProvider.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libConfigSettingProvider.so /opt/microsoft/scx/lib/providers/libConfigSettingProvider.so
rm /opt/microsoft/scx/lib/providers/libConfigSettingProvider.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libConfigSettingProvider.so /opt/microsoft/scx/lib/providers/libConfigSettingProvider.so.1
rm /opt/microsoft/scx/lib/libDefaultProviderManager.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libDefaultProviderManager.so /opt/microsoft/scx/lib/libDefaultProviderManager.so
rm /opt/microsoft/scx/lib/libDefaultProviderManager.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libDefaultProviderManager.so /opt/microsoft/scx/lib/libDefaultProviderManager.so.1
rm /opt/microsoft/scx/lib/libpegCLIClientLib.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegCLIClientLib.so /opt/microsoft/scx/lib/libpegCLIClientLib.so
rm /opt/microsoft/scx/lib/libpegCLIClientLib.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegCLIClientLib.so /opt/microsoft/scx/lib/libpegCLIClientLib.so.1
rm /opt/microsoft/scx/lib/providers/libInteropProvider.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libInteropProvider.so /opt/microsoft/scx/lib/providers/libInteropProvider.so
rm /opt/microsoft/scx/lib/providers/libInteropProvider.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libInteropProvider.so.1 /opt/microsoft/scx/lib/providers/libInteropProvider.so.1
rm /opt/microsoft/scx/lib/providers/libNamespaceProvider.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libNamespaceProvider.so /opt/microsoft/scx/lib/providers/libNamespaceProvider.so
rm /opt/microsoft/scx/lib/providers/libNamespaceProvider.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libNamespaceProvider.so /opt/microsoft/scx/lib/providers/libNamespaceProvider.so.1
rm /opt/microsoft/scx/lib/providers/libOSProvider.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libOSProvider.so /opt/microsoft/scx/lib/providers/libOSProvider.so
rm /opt/microsoft/scx/lib/providers/libOSProvider.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libOSProvider.so /opt/microsoft/scx/lib/providers/libOSProvider.so.1
rm /opt/microsoft/scx/lib/libpegauthentication.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegauthentication.so /opt/microsoft/scx/lib/libpegauthentication.so
rm /opt/microsoft/scx/lib/libpegauthentication.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegauthentication.so /opt/microsoft/scx/lib/libpegauthentication.so.1
rm /opt/microsoft/scx/lib/libpegclient.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegclient.so /opt/microsoft/scx/lib/libpegclient.so
rm /opt/microsoft/scx/lib/libpegclient.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegclient.so /opt/microsoft/scx/lib/libpegclient.so.1
rm /opt/microsoft/scx/lib/libpegcliutils.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegcliutils.so /opt/microsoft/scx/lib/libpegcliutils.so
rm /opt/microsoft/scx/lib/libpegcliutils.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegcliutils.so /opt/microsoft/scx/lib/libpegcliutils.so.1
rm /opt/microsoft/scx/lib/libpegcommon.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegcommon.so /opt/microsoft/scx/lib/libpegcommon.so
rm /opt/microsoft/scx/lib/libpegcommon.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegcommon.so /opt/microsoft/scx/lib/libpegcommon.so.1
rm /opt/microsoft/scx/lib/libpegcompiler.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegcompiler.so /opt/microsoft/scx/lib/libpegcompiler.so
rm /opt/microsoft/scx/lib/libpegcompiler.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegcompiler.so /opt/microsoft/scx/lib/libpegcompiler.so.1
rm /opt/microsoft/scx/lib/libpegconfig.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegconfig.so /opt/microsoft/scx/lib/libpegconfig.so
rm /opt/microsoft/scx/lib/libpegconfig.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegconfig.so /opt/microsoft/scx/lib/libpegconfig.so.1
rm /opt/microsoft/scx/lib/libpegcql.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegcql.so /opt/microsoft/scx/lib/libpegcql.so
rm /opt/microsoft/scx/lib/libpegcql.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegcql.so /opt/microsoft/scx/lib/libpegcql.so.1
rm /opt/microsoft/scx/lib/libpegexportclient.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegexportclient.so /opt/microsoft/scx/lib/libpegexportclient.so
rm /opt/microsoft/scx/lib/libpegexportclient.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegexportclient.so /opt/microsoft/scx/lib/libpegexportclient.so.1
rm /opt/microsoft/scx/lib/libpegexportserver.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegexportserver.so /opt/microsoft/scx/lib/libpegexportserver.so
rm /opt/microsoft/scx/lib/libpegexportserver.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegexportserver.so /opt/microsoft/scx/lib/libpegexportserver.so.1
rm /opt/microsoft/scx/lib/libpeggetoopt.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpeggetoopt.so /opt/microsoft/scx/lib/libpeggetoopt.so
rm /opt/microsoft/scx/lib/libpeggetoopt.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpeggetoopt.so /opt/microsoft/scx/lib/libpeggetoopt.so.1
rm /opt/microsoft/scx/lib/libpeghandlerservice.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpeghandlerservice.so /opt/microsoft/scx/lib/libpeghandlerservice.so
rm /opt/microsoft/scx/lib/libpeghandlerservice.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpeghandlerservice.so /opt/microsoft/scx/lib/libpeghandlerservice.so.1
rm /opt/microsoft/scx/lib/libpegindicationservice.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegindicationservice.so /opt/microsoft/scx/lib/libpegindicationservice.so
rm /opt/microsoft/scx/lib/libpegindicationservice.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegindicationservice.so /opt/microsoft/scx/lib/libpegindicationservice.so.1
rm /opt/microsoft/scx/lib/libpegpmservice.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegpmservice.so /opt/microsoft/scx/lib/libpegpmservice.so
rm /opt/microsoft/scx/lib/libpegpmservice.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegpmservice.so /opt/microsoft/scx/lib/libpegpmservice.so.1
rm /opt/microsoft/scx/lib/libpegprm.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegprm.so /opt/microsoft/scx/lib/libpegprm.so
rm /opt/microsoft/scx/lib/libpegprm.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegprm.so /opt/microsoft/scx/lib/libpegprm.so.1
rm /opt/microsoft/scx/lib/libpegprovidermanager.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegprovidermanager.so /opt/microsoft/scx/lib/libpegprovidermanager.so
rm /opt/microsoft/scx/lib/libpegprovidermanager.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegprovidermanager.so /opt/microsoft/scx/lib/libpegprovidermanager.so.1
rm /opt/microsoft/scx/lib/providers/libpegprovider.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegprovider.so /opt/microsoft/scx/lib/providers/libpegprovider.so
rm /opt/microsoft/scx/lib/providers/libpegprovider.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegprovider.so /opt/microsoft/scx/lib/providers/libpegprovider.so.1
rm /opt/microsoft/scx/lib/libpegquerycommon.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegquerycommon.so /opt/microsoft/scx/lib/libpegquerycommon.so
rm /opt/microsoft/scx/lib/libpegquerycommon.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegquerycommon.so /opt/microsoft/scx/lib/libpegquerycommon.so.1
rm /opt/microsoft/scx/lib/libpegqueryexpression.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegqueryexpression.so /opt/microsoft/scx/lib/libpegqueryexpression.so
rm /opt/microsoft/scx/lib/libpegqueryexpression.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegqueryexpression.so /opt/microsoft/scx/lib/libpegqueryexpression.so.1
rm /opt/microsoft/scx/lib/libpegrepository.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegrepository.so /opt/microsoft/scx/lib/libpegrepository.so
rm /opt/microsoft/scx/lib/libpegrepository.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegrepository.so /opt/microsoft/scx/lib/libpegrepository.so.1
rm /opt/microsoft/scx/lib/libpegserver.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegserver.so /opt/microsoft/scx/lib/libpegserver.so
rm /opt/microsoft/scx/lib/libpegserver.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegserver.so /opt/microsoft/scx/lib/libpegserver.so.1
rm /opt/microsoft/scx/lib/libpegservice.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegservice.so /opt/microsoft/scx/lib/libpegservice.so
rm /opt/microsoft/scx/lib/libpegservice.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegservice.so /opt/microsoft/scx/lib/libpegservice.so.1
rm /opt/microsoft/scx/lib/libpeguser.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpeguser.so /opt/microsoft/scx/lib/libpeguser.so
rm /opt/microsoft/scx/lib/libpeguser.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpeguser.so /opt/microsoft/scx/lib/libpeguser.so.1
rm /opt/microsoft/scx/lib/libpegwql.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegwql.so /opt/microsoft/scx/lib/libpegwql.so
rm /opt/microsoft/scx/lib/libpegwql.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libpegwql.so /opt/microsoft/scx/lib/libpegwql.so.1
rm /opt/microsoft/scx/lib/providers/libProviderRegistrationProvider.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libProviderRegistrationProvider.so /opt/microsoft/scx/lib/providers/libProviderRegistrationProvider.so
rm /opt/microsoft/scx/lib/providers/libProviderRegistrationProvider.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libProviderRegistrationProvider.so /opt/microsoft/scx/lib/providers/libProviderRegistrationProvider.so.1
rm /opt/microsoft/scx/lib/providers/libUserAuthProvider.so; ln -s $PEG_STAGING_ROOT_DIR/lib/libUserAuthProvider.so /opt/microsoft/scx/lib/providers/libUserAuthProvider.so
rm /opt/microsoft/scx/lib/providers/libUserAuthProvider.so.1; ln -s $PEG_STAGING_ROOT_DIR/lib/libUserAuthProvider.so /opt/microsoft/scx/lib/providers/libUserAuthProvider.so.1
rm /opt/microsoft/scx/lib/providers/libSCXCoreProviderModule.so; ln -s $TARGET_STAGING_ROOT_DIR/libSCXCoreProviderModule.so /opt/microsoft/scx/lib/providers/libSCXCoreProviderModule.so
#rm /opt/microsoft/scx/lib/providers/libSCXCoreProviderModule.so.1; ln -s $TARGET_STAGING_ROOT_DIR/libSCXCoreProviderModule.so /opt/microsoft/scx/lib/providers/libSCXCoreProviderModule.so

rm /opt/microsoft/scx/lib/providers/ext/libSCXTestProviderModule.so; ln -s $TARGET_STAGING_ROOT_DIR/libSCXTestProviderModule.so /opt/microsoft/scx/lib/providers/ext/libSCXTestProviderModule.so
rm /opt/microsoft/scx/lib/providers/ext/libSCXTestProviderModule.so.1; ln -s $TARGET_STAGING_ROOT_DIR/libSCXTestProviderModule.so /opt/microsoft/scx/lib/providers/ext/libSCXTestProviderModule.so.1

#--------------------------------------------------------------------------------
# OpenWSMan

#rm /opt/microsoft/scx/lib/libwsman_client.so; ln -s $WSM_STAGING_ROOT_DIR/lib/libwsman_client.so /opt/microsoft/scx/lib/libwsman_client.so
#rm /opt/microsoft/scx/lib/libwsman_client.so.1; ln -s $WSM_STAGING_ROOT_DIR/lib/libwsman_client.so /opt/microsoft/scx/lib/libwsman_client.so.1

#rm /opt/microsoft/scx/lib/libwsman_curl_client_transport.so; ln -s $WSM_STAGING_ROOT_DIR/lib/libwsman_curl_client_transport.so /opt/microsoft/scx/lib/libwsman_curl_client_transport.so
#rm /opt/microsoft/scx/lib/libwsman_curl_client_transport.so.1; ln -s $WSM_STAGING_ROOT_DIR/lib/libwsman_curl_client_transport.so /opt/microsoft/scx/lib/libwsman_curl_client_transport.so.1

rm /opt/microsoft/scx/lib/libwsman_server.so; ln -s $WSM_STAGING_ROOT_DIR/lib/libwsman_server.so /opt/microsoft/scx/lib/libwsman_server.so
rm /opt/microsoft/scx/lib/libwsman_server.so.1; ln -s $WSM_STAGING_ROOT_DIR/lib/libwsman_server.so /opt/microsoft/scx/lib/libwsman_server.so.1

rm /opt/microsoft/scx/lib/libwsman.so; ln -s $WSM_STAGING_ROOT_DIR/lib/libwsman.so /opt/microsoft/scx/lib/libwsman.so
rm /opt/microsoft/scx/lib/libwsman.so.1; ln -s $WSM_STAGING_ROOT_DIR/lib/libwsman.so /opt/microsoft/scx/lib/libwsman.so.1


#--------------------------------------------------------------------------------

# lib/openwsman/authenticators
rm /opt/microsoft/scx/lib/openwsman/authenticators/libwsman_pam_auth.so; ln -s $WSM_STAGING_ROOT_DIR/lib/openwsman/authenticators/libwsman_pam_auth.so /opt/microsoft/scx/lib/openwsman/authenticators/libwsman_pam_auth.so
# lib/openwsman/plugins
rm /opt/microsoft/scx/lib/openwsman/plugins/libwsman_cim_plugin.so; ln -s $WSM_STAGING_ROOT_DIR/lib/openwsman/plugins/libwsman_cim_plugin.so /opt/microsoft/scx/lib/openwsman/plugins/libwsman_cim_plugin.so

#--------------------------------------------------------------------------------
# Repositories

rm -rf /var/opt/microsoft/scx/lib/repository; ln -s $PEG_STAGING_ROOT_DIR/repository /var/opt/microsoft/scx/lib/repository
